# Copyright (c) 2023 Boston Dynamics AI Institute LLC.  All rights reserved.
load("@rules_python//python/pip_install:requirements.bzl", "compile_pip_requirements")

compile_pip_requirements(
    name = "scripts_requirements",
    requirements_in = "scripts.requirements.txt",
    requirements_txt = "scripts.requirements.lock.txt",
)
